In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Employee-Attrition.csv')

In [3]:
df

Attrition  Age     BusinessTravel  DailyRate              Department  \
0          Yes   41      Travel_Rarely       1102                   Sales   
1           No   49  Travel_Frequently        279  Research & Development   
2          Yes   37      Travel_Rarely       1373  Research & Development   
3           No   33  Travel_Frequently       1392  Research & Development   
4           No   27      Travel_Rarely        591  Research & Development   
...        ...  ...                ...        ...                     ...   
1465        No   36  Travel_Frequently        884  Research & Development   
1466        No   39      Travel_Rarely        613  Research & Development   
1467        No   27      Travel_Rarely        155  Research & Development   
1468        No   49  Travel_Frequently       1023                   Sales   
1469        No   34      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9   

In [4]:
df.isnull().sum()

Attrition                   0
Age                         0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

In [5]:
df.cov()

Age      DailyRate  DistanceFromHome  \
Age                          83.455049      39.298434         -0.124873   
DailyRate                    39.298434  162819.593737        -16.308004   
DistanceFromHome             -0.124873     -16.308004         65.721251   
Education                     1.946390      -6.945424          0.174705   
EmployeeCount                 0.000000       0.000000          0.000000   
EmployeeNumber              -55.797199  -12386.713294        160.649502   
EnvironmentSatisfaction       0.101319       8.095750         -0.142451   
HourlyRate                    4.510422     191.800350          5.130567   
JobInvolvement                0.193841      13.246309          0.050667   
JobLevel                      5.153276       1.324944          0.047586   
JobSatisfaction              -0.049285      13.604357         -0.032802   
MonthlyIncome             21412.198982   14641.125975       -649.386355   
MonthlyRate                1823.988823  -92428.502266       1585.264627   
NumCompaniesWorked            6.837739      38.457493         -0.592359   
PercentSalaryHike             0.121489      33.529204          1.193809   
PerformanceRating             0.006276       0.068910          0.079300   
RelationshipSatisfaction      0.528776       3.423048          0.057478   
StandardHours                 0.000000       0.000000          0.000000   
StockOptionLevel              0.291977      14.489565          0.309961   
TotalWorkingYears            48.361684      45.570709          0.291951   
TrainingTimesLastYear        -0.231093       1.275892         -0.386118   
WorkLifeBalance              -0.138695     -10.789322         -0.152094   
YearsAtCompany               17.423359     -84.187085          0.472219   
YearsInCurrentRole            7.046750      14.520296          0.553521   
YearsSinceLastPromotion       6.373743     -43.206982          0.261991   
YearsWithCurrManager          6.587332     -37.957055          0.416715   

                           Education  EmployeeCount  EmployeeNumber  \
Age                         1.946390            0.0      -55.797199   
DailyRate                  -6.945424            0.0   -12386.713294   
DistanceFromHome            0.174705            0.0      160.649502   
Education                   1.048914            0.0       25.939251   
EmployeeCount               0.000000            0.0        0.000000   
EmployeeNumber             25.939251            0.0   362433.299749   
EnvironmentSatisfaction    -0.030370            0.0       11.595582   
HourlyRate                  0.349263            0.0      430.551701   
JobInvolvement              0.030927            0.0       -2.950629   
JobLevel                    0.115170            0.0      -12.341279   
JobSatisfaction            -0.012759            0.0      -30.705067   
MonthlyIncome             457.874204            0.0   -42028.530023   
MonthlyRate              -190.148240            0.0    54198.679015   
NumCompaniesWorked          0.323165            0.0       -1.881380   
PercentSalaryHike          -0.041648            0.0      -28.520432   
PerformanceRating          -0.009068            0.0       -4.422436   
RelationshipSatisfaction   -0.010097            0.0      -45.473775   
StandardHours               0.000000            0.0        0.000000   
StockOptionLevel            0.016076            0.0       31.920482   
TotalWorkingYears           1.181612            0.0      -67.289749   
TrainingTimesLastYear      -0.033143            0.0       18.320126   
WorkLifeBalance             0.007105            0.0        4.384426   
YearsAtCompany              0.433659            0.0      -41.458396   
YearsInCurrentRole          0.223515            0.0      -18.357800   
YearsSinceLastPromotion     0.179056            0.0      -17.496817   
YearsWithCurrManager        0.252390            0.0      -19.755358   

                          EnvironmentSatisfaction   HourlyRate  \
Age                      

In [6]:
df.corr()

Age  DailyRate  DistanceFromHome  Education  \
Age                       1.000000   0.010661         -0.001686   0.208034   
DailyRate                 0.010661   1.000000         -0.004985  -0.016806   
DistanceFromHome         -0.001686  -0.004985          1.000000   0.021042   
Education                 0.208034  -0.016806          0.021042   1.000000   
EmployeeCount                  NaN        NaN               NaN        NaN   
EmployeeNumber           -0.010145  -0.050990          0.032916   0.042070   
EnvironmentSatisfaction   0.010146   0.018355         -0.016075  -0.027128   
HourlyRate                0.024287   0.023381          0.031131   0.016775   
JobInvolvement            0.029820   0.046135          0.008783   0.042438   
JobLevel                  0.509604   0.002966          0.005303   0.101589   
JobSatisfaction          -0.004892   0.030571         -0.003669  -0.011296   
MonthlyIncome             0.497855   0.007707         -0.017014   0.094961   
MonthlyRate               0.028051  -0.032182          0.027473  -0.026084   
NumCompaniesWorked        0.299635   0.038153         -0.029251   0.126317   
PercentSalaryHike         0.003634   0.022704          0.040235  -0.011111   
PerformanceRating         0.001904   0.000473          0.027110  -0.024539   
RelationshipSatisfaction  0.053535   0.007846          0.006557  -0.009118   
StandardHours                  NaN        NaN               NaN        NaN   
StockOptionLevel          0.037510   0.042143          0.044872   0.018422   
TotalWorkingYears         0.680381   0.014515          0.004628   0.148280   
TrainingTimesLastYear    -0.019621   0.002453         -0.036942  -0.025100   
WorkLifeBalance          -0.021490  -0.037848         -0.026556   0.009819   
YearsAtCompany            0.311309  -0.034055          0.009508   0.069114   
YearsInCurrentRole        0.212901   0.009932          0.018845   0.060236   
YearsSinceLastPromotion   0.216513  -0.033229          0.010029   0.054254   
YearsWithCurrManager      0.202089  -0.026363          0.014406   0.069065   

                          EmployeeCount  EmployeeNumber  \
Age                                 NaN       -0.010145   
DailyRate                           NaN       -0.050990   
DistanceFromHome                    NaN        0.032916   
Education                           NaN        0.042070   
EmployeeCount                       NaN             NaN   
EmployeeNumber                      NaN        1.000000   
EnvironmentSatisfaction             NaN        0.017621   
HourlyRate                          NaN        0.035179   
JobInvolvement                      NaN       -0.006888   
JobLevel                            NaN       -0.018519   
JobSatisfaction                     NaN       -0.046247   
MonthlyIncome                       NaN       -0.014829   
MonthlyRate                         NaN        0.012648   
NumCompaniesWorked                  NaN       -0.001251   
PercentSalaryHike                   NaN       -0.012944   
PerformanceRating                   NaN       -0.020359   
RelationshipSatisfaction            NaN       -0.069861   
StandardHours                       NaN             NaN   
StockOptionLevel                    NaN        0.062227   
TotalWorkingYears                   NaN       -0.014365   
TrainingTimesLastYear               NaN        0.023603   
WorkLifeBalance                     NaN        0.010309   
YearsAtCompany                      NaN       -0.011240   
YearsInCurrentRole                  NaN       -0.008416   
YearsSinceLastPromotion             NaN       -0.009019   
YearsWithCurrManager                NaN       -0.009197   

                          EnvironmentSatisfaction  HourlyRate  JobInvolvement  \
Age                                      0.010146    0.024287        0.029820   
DailyRate                                0.018355    0.023381        0.046135   
DistanceFromHome                        -0.016075    0.031131        0.008783   
Educat

In [7]:
yes_class=df[df['Attrition'].str.contains('Yes')]

In [8]:

yes_class

Attrition  Age     BusinessTravel  DailyRate              Department  \
0          Yes   41      Travel_Rarely       1102                   Sales   
2          Yes   37      Travel_Rarely       1373  Research & Development   
14         Yes   28      Travel_Rarely        103  Research & Development   
21         Yes   36      Travel_Rarely       1218                   Sales   
24         Yes   34      Travel_Rarely        699  Research & Development   
...        ...  ...                ...        ...                     ...   
1438       Yes   23  Travel_Frequently        638                   Sales   
1442       Yes   29      Travel_Rarely       1092  Research & Development   
1444       Yes   56      Travel_Rarely        310  Research & Development   
1452       Yes   50  Travel_Frequently        878                   Sales   
1461       Yes   50      Travel_Rarely        410                   Sales   

      DistanceFromHome  Education    EducationField  EmployeeCount  \
0                    1          2     Life Sciences              1   
2                    2          2             Other              1   
14                  24          3     Life Sciences              1   
21                   9          4     Life Sciences              1   
24                   6          1           Medical              1   
...                ...        ...               ...            ...   
1438                 9          3         Marketing              1   
1442                 1          4           Medical              1   
1444                 7          2  Technical Degree              1   
1452                 1          4     Life Sciences              1   
1461                28          3         Marketing              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
2                  4  ...                         2            80   
14                19  ...                         2            80   
21                27  ...                         2            80   
24                31  ...                         3            80   
...              ...  ...                       ...           ...   
1438            2023  ...                         1            80   
1442            2027  ...                         2            80   
1444            2032  ...                         4            80   
1452            2044  ...                         4            80   
1461            2055  ...                         2            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
2                    0                  7                      3   
14                   0                  6                      4   
21                   0                 10                      4   
24                   0                  8                      2   
...                ...                ...                    ...   
1438                 1                  1                      3   
1442                 3                  4                      3   
1444                 1                 14                      4   
1452                 2                 12                      3   
1461                 1                 20                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
2                  3               0                  0   
14                 3               4                  2   
21                 3               5                  3   
24                 3               4                  2   
...              ...             ...                ...   
1438               2               1                  0   
1442               4               2                  2   
1444               1              10                  9   
145

In [9]:
no_class=df[df['Attrition'].str.contains('No')]

In [10]:
no_class

Attrition  Age     BusinessTravel  DailyRate              Department  \
1           No   49  Travel_Frequently        279  Research & Development   
3           No   33  Travel_Frequently       1392  Research & Development   
4           No   27      Travel_Rarely        591  Research & Development   
5           No   32  Travel_Frequently       1005  Research & Development   
6           No   59      Travel_Rarely       1324  Research & Development   
...        ...  ...                ...        ...                     ...   
1465        No   36  Travel_Frequently        884  Research & Development   
1466        No   39      Travel_Rarely        613  Research & Development   
1467        No   27      Travel_Rarely        155  Research & Development   
1468        No   49  Travel_Frequently       1023                   Sales   
1469        No   34      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
1                    8          1  Life Sciences              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
5                    2          2  Life Sciences              1   
6                    3          3        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
1                  2  ...                         4            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
5                  8  ...                         3            80   
6                 10  ...                         1            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
1                    1                 10                      3   
3                    0                  8                      3   
4                    1                  6                      3   
5                    0                  8                      2   
6                    3                 12                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
1                  3              10                  7   
3                  3               8                  7   
4                  3               2                  2   
5                  2               7                  7   
6                  2               1                  0   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9   

In [11]:
yes_class['Age'].mean()

33.607594936708864

In [12]:
no_class['Age'].mean()

37.561232765612324

In [13]:
yes_class['DistanceFromHome'].mean()

10.632911392405063

In [14]:
no_class['DistanceFromHome'].mean()

8.915652879156529

In [15]:
yes_class.describe()

Age    DailyRate  DistanceFromHome   Education  EmployeeCount  \
count  237.000000   237.000000        237.000000  237.000000          237.0   
mean    33.607595   750.362869         10.632911    2.839662            1.0   
std      9.689350   401.899519          8.452525    1.008244            0.0   
min     18.000000   103.000000          1.000000    1.000000            1.0   
25%     28.000000   408.000000          3.000000    2.000000            1.0   
50%     32.000000   699.000000          9.000000    3.000000            1.0   
75%     39.000000  1092.000000         17.000000    4.000000            1.0   
max     58.000000  1496.000000         29.000000    5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction  HourlyRate  JobInvolvement  \
count      237.000000               237.000000  237.000000      237.000000   
mean      1010.345992                 2.464135   65.573840        2.518987   
std        580.750572                 1.169791   20.099958        0.773405   
min          1.000000                 1.000000   31.000000        1.000000   
25%        514.000000                 1.000000   50.000000        2.000000   
50%       1017.000000                 3.000000   66.000000        3.000000   
75%       1486.000000                 4.000000   84.000000        3.000000   
max       2055.000000                 4.000000  100.000000        4.000000   

         JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  237.000000  ...                237.000000          237.0   
mean     1.637131  ...                  2.599156           80.0   
std      0.940594  ...                  1.125437            0.0   
min      1.000000  ...                  1.000000           80.0   
25%      1.000000  ...                  2.000000           80.0   
50%      1.000000  ...                  3.000000           80.0   
75%      2.000000  ...                  4.000000           80.0   
max      5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count        237.000000         237.000000             237.000000   
mean           0.527426           8.244726               2.624473   
std            0.856361           7.169204               1.254784   
min            0.000000           0.000000               0.000000   
25%            0.000000           3.000000               2.000000   
50%            0.000000           7.000000               2.000000   
75%            1.000000          10.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count       237.000000      237.000000          237.000000   
mean          2.658228        5.130802            2.902954   
std           0.816453        5.949984            3.174827   
min           1.000000        0.000000            0.000000   
25%           2.000000        1.000000            0.000000   
50%           3.000000        3.000000            2.000000   
75%           3.000000        7.000000            4.000000   
max           4.000000       40.000000           15.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count               237.000000            237.000000  
mean                  1.945148              2.852321  
std                   3.153077              3.143349  
min                   0.000000              0.000000  
25%                   0.000000              0.000000  
50%                   1.000000              2.000000  
75%                   2.000000              5.000000  
max                  15.000000             14.000000  

[8 rows x 26 columns]

In [16]:
no_class.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1233.000000  1233.000000       1233.000000  1233.000000         1233.0   
mean     37.561233   812.504461          8.915653     2.927007            1.0   
std       8.888360   403.208379          8.012633     1.027002            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      31.000000   477.000000          2.000000     2.000000            1.0   
50%      36.000000   817.000000          7.000000     3.000000            1.0   
75%      43.000000  1176.000000         13.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1233.000000              1233.000000  1233.000000     1233.000000   
mean      1027.656123                 2.771290    65.952149        2.770479   
std        606.217074                 1.071132    20.380754        0.692050   
min          2.000000                 1.000000    30.000000        1.000000   
25%        483.000000                 2.000000    48.000000        2.000000   
50%       1022.000000                 3.000000    66.000000        3.000000   
75%       1574.000000                 4.000000    83.000000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1233.000000  ...               1233.000000         1233.0   
mean      2.145985  ...                  2.733982           80.0   
std       1.117933  ...                  1.071603            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1233.000000        1233.000000            1233.000000   
mean           0.845093          11.862936               2.832928   
std            0.841985           7.760719               1.293585   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          16.000000               3.000000   
max            3.000000          38.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1233.000000     1233.000000         1233.000000   
mean          2.781022        7.369019            4.484185   
std           0.681907        6.096298            3.649402   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        6.000000            3.000000   
75%           3.000000       10.000000            7.000000   
max           4.000000       37.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1233.000000           1233.000000  
mean                  2.234388              4.367397  
std                   3.234762              3.594116  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

In [17]:
df.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1470.000000  ...               1470.000000         1470.0   
mean      2.063946  ...                  2.712245           80.0   
std       1.106940  ...                  1.081209            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

In [18]:
import chart_studio.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode

In [19]:
#Using plotly + cufflinks in offline mode
import cufflinks
cufflinks.go_offline(connected=True)
init_notebook_mode(connected=True)

In [20]:
#Plot a Bivariate Scatter Plot
df.iplot(
    x='Age',
    y='EnvironmentSatisfaction',
    categories='Attrition',
    xTitle='Age',
    yTitle='EnvSatisfaction',
    title='Age vs EnvSatisfaction')

C:\Users\personal\anaconda3\lib\site-packages\cufflinks\plotlytools.py:807: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

C:\Users\personal\anaconda3\lib\site-packages\cufflinks\plotlytools.py:810: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead



# This plot shows us that less age people tend to leave

In [21]:
df.iplot(
    x='DailyRate',
    y='Education',
    categories='Attrition',
    xTitle='DailyRate',
    yTitle='Education',
    title='DailyRate vs Education')

# Labelencoding and onehotencoding

In [22]:
x=df.iloc[:,1:35].values
y=df.iloc[:,0:1].values


In [23]:
print(x)

[[41 'Travel_Rarely' 1102 ... 4 0 5]
 [49 'Travel_Frequently' 279 ... 7 1 7]
 [37 'Travel_Rarely' 1373 ... 0 0 0]
 ...
 [27 'Travel_Rarely' 155 ... 2 0 3]
 [49 'Travel_Frequently' 1023 ... 6 0 8]
 [34 'Travel_Rarely' 628 ... 3 1 2]]


In [24]:
print(y)

[['Yes']
 ['No']
 ['Yes']
 ...
 ['No']
 ['No']
 ['No']]


In [25]:
#from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#l = LabelEncoder() 
#df['Attrition']=l.fit_transform(df['Attrition'])
#df['BusinessTravel'] = l.fit_transform(df['BusinessTravel'])
#oh=OneHotEncoder(categories = 'auto')
#x = oh.fit_transform(x).toarray()

#df['Department'] = oh.fit_transform(x).toarray()
#df['EducationField'] = oh.fit_transform(x).toarray()

In [26]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(categories='auto')
x=oh.fit_transform(x).toarray()

lb=LabelEncoder()

y=lb.fit_transform(y) 
y.reshape(-1,1)



C:\Users\personal\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



array([[1],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [48]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Feature Scaling


In [28]:
from sklearn import preprocessing
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
print(df.shape)

(1470, 35)


In [30]:
df.isnull().sum()

Attrition                   0
Age                         0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

# Splitting data into training and testing sets

In [31]:
#Splitting the dataset into Training set=70% and Test set=30%
from sklearn import model_selection, neighbors
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=1)

In [32]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [34]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [35]:
y_test = y_test.astype('int')
y_test

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [36]:
print("X_train:",len(x_train))
print("X_test:",len(x_test))
print("Y_train:",len(y_train))
print("Y_test:",len(y_test))

X_train: 1029
X_test: 441
Y_train: 1029
Y_test: 441


In [37]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, recall_score, roc_auc_score, confusion_matrix
rf = RandomForestClassifier(n_estimators=15,criterion="entropy")
rmf_clf=rf.fit(x_train,y_train)

In [38]:
from sklearn import metrics
print("Random Forest")
print("Accuracy: ",rf.score(x_test,y_test))
y_pred = rf.predict(x_test)
print("Precision: ",metrics.precision_score(y_test,y_pred))
print("Recall: ",metrics.recall_score(y_test,y_pred))
print("Confusion Matrix: \n",metrics.confusion_matrix(y_test,y_pred))

Random Forest
Accuracy:  0.8299319727891157
Precision:  0.75
Recall:  0.03896103896103896
Confusion Matrix: 
 [[363   1]
 [ 74   3]]


In [39]:
majority_class = df[df['Attrition']==0]
minority_class = df[df['Attrition']==1]
print(len(majority_class))
print(len(minority_class))

0
0


In [40]:
y_pred=rmf_clf.predict(x_test)

In [41]:
rmf_cm_test = confusion_matrix(y_test,y_pred)
rmf_cm_test

array([[363,   1],
       [ 74,   3]], dtype=int64)

In [42]:
#Accuracy score on Test and Train
from sklearn.metrics import accuracy_score, recall_score, roc_auc_score, confusion_matrix
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred) * 100))
print("Recall score : %f" %(recall_score(y_test, y_pred) * 100))
print("ROC score : %f\n" %(roc_auc_score(y_test, y_pred) * 100))
print(confusion_matrix(y_test, y_pred)) 


Accuracy score: 82.993197
Recall score : 3.896104
ROC score : 51.810689

[[363   1]
 [ 74   3]]


In [43]:
y_pred=rmf_clf.predict(x_train)

In [44]:
rmf_cm_train = confusion_matrix(y_train,y_pred)
rmf_cm_train

array([[869,   0],
       [ 15, 145]], dtype=int64)

In [45]:
precision=rmf_cm_train[0][0]/(rmf_cm_train[0][0]+rmf_cm_train[0][1])
precision

1.0

In [46]:
from sklearn.metrics import accuracy_score, recall_score, roc_auc_score, confusion_matrix
print("\nAccuracy score: %f" %(accuracy_score(y_train,y_pred) * 100))
print("Recall score : %f" %(recall_score(y_train, y_pred) * 100))
print("ROC score : %f\n" %(roc_auc_score(y_train, y_pred) * 100))
print(confusion_matrix(y_train, y_pred)) 


Accuracy score: 98.542274
Recall score : 90.625000
ROC score : 95.312500

[[869   0]
 [ 15 145]]
